
{{- range .Values.databases }}
---
apiVersion: mdb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: PostgresqlDatabase
metadata:
  name: {{.dbname }}
spec:
  forProvider:
    clusterIdRef:
      name: {{ $.Release.Name }}
    name: {{.dbname }}
    owner: {{.owner }}
---
{{- end }} 
