{{- range .Values.users }}
---
kind: Secret
apiVersion: v1
metadata:
  name: pass-{{ .name }}
data:
  {{- if $.Release.IsInstall }}
  password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- else }}
  password: {{ (lookup "v1" "Secret" $.Release.Namespace (print "pass-" .name)).data.password }}
  {{ end }}
---
{{- end }} 
