{{- $fullName := include "my-app.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 2
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "my-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
          {{- with (index  .Values.users 0) }}
            - name: DB_USER
              value: {{ $fullName }}-{{ .name }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pass-{{ .name }}
                  key: password
          {{- end }} 
          {{- with (index  .Values.databases 0) }}
            - name: DB_HOST
              value: {{ .transfer.fromclusterFQDN }}
            - name: DB_PORT
              value: "{{ .dbport }}"
            - name: DB_NAME
              value: {{ $fullName }}-{{ .dbname }}
          {{- end }} 
            - name: SERVICE_ONE
              value: {{ .Values.serviceOne }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
