{{- $fullName := include "my-app.fullname" . -}}
{{- range .Values.databases }}
  {{- if .transfer -}}
  {{- $owner := .owner -}}
    {{- with .transfer -}}
---
apiVersion: datatransfer.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Endpoint
metadata:
  name: {{ $fullName }}-source
spec:
  forProvider:
    folderId: {{ $.Values.folderID }}
    name: {{ $fullName }}-source
    settings:
      - postgresSource:
        - database: {{ .fromdb }}
          password:
            - rawSecretRef:
                name: pass-{{ .user }}
                namespace: {{ .fromnamespace }}
                key: password
          user: {{ .user }}
          connection:
          - mdbClusterIdRef:
              name: {{ .fromcluster }}
    {{- end }} 
---
apiVersion: datatransfer.yandex-cloud.jet.crossplane.io/v1alpha1 
kind: Endpoint
metadata:
  name: {{ $fullName }}-target
spec:
  forProvider:
    name: {{ $fullName }}-target
    folderId: {{ $.Values.folderID }}
    settings:
      - postgresTarget:
        - database: {{ $fullName }}-{{ .dbname }}
        {{- range $.Values.users -}}
          {{ if eq .name $owner }} # выбираем пользователя eq владелец, берем его secret
          password:
            - rawSecretRef:
                name: pass-{{ .name }}
                namespace: {{ $.Release.Namespace }}
                key: password
          {{- end }} 
        {{- end }} 
          user: {{ $fullName }}-{{ .owner }}
          connection:
          - mdbClusterIdRef:
              name: {{ .transfer.fromcluster  }}

---
apiVersion: datatransfer.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Transfer
metadata:
  name: {{ $fullName }}-transfer
spec:
  forProvider:
    name: {{ $fullName }}-transfer
    sourceIdRef:
      name: {{ $fullName }}-source
    targetIdRef:
      name: {{ $fullName }}-target
    type: "SNAPSHOT_AND_INCREMENT"
    folderId: {{ $.Values.folderID }}
  {{- end }} 
{{- end }} 
